language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get update
  - sudo apt-get install -y git curl wget

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./deploy.sh; fi'

branches:
  only:
    - master