version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/wsxxsy/v2ray-domain-list
    steps:
      - add_ssh_keys:
          fingerprints:
            - "17:e0:e1:96:16:9b:0e:3f:b0:e4:ac:30:25:ef:cd:4b"
      - checkout
      - run: 
          name: Before
          command: |
            mkdir -p dat ip site
            rm -rf dat/* ip/* site/*
            wget -O geoip.dat https://github.com/v2ray/geoip/releases/latest/download/geoip.dat
            wget -O geosite.dat https://github.com/v2ray/domain-list-community/releases/latest/download/dlc.dat
            wget -O sr_top500_banlist_ad.conf https://raw.githubusercontent.com/h2y/Shadowrocket-ADBlock-Rules/master/sr_top500_banlist_ad.conf
            cat sr_top500_banlist_ad.conf | grep Reject | grep IP-CIDR | awk -F, '{print $2}' > ip/ad
            cat sr_top500_banlist_ad.conf | grep Reject | grep DOMAIN-SUFFIX | awk -F, '{print $2}' > site/ad
            cat sr_top500_banlist_ad.conf | grep Proxy | grep IP-CIDR | awk -F, '{print $2}' > ip/gfw
            cat sr_top500_banlist_ad.conf | grep Proxy | grep DOMAIN-SUFFIX | awk -F, '{print $2}' > site/gfw
      - restore_cache:
          keys:
              - go-mod-v1-{{ checksum "go.sum" }}
      - run: 
          name: Build
          command: go run main.go
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
              - /go/pkg/mod
      - run: 
          name: After
          command: |
            rm -rf geoip.dat geosite.dat sr_top500_banlist_ad.conf
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config user.name CircleCi
            git add .
            git commit -m ':art: Daily build'
            git push -u origin master
workflows:
  version: 2
  monthly:
    triggers:
       - schedule:
          cron: "0 0 1 * *"
          filters:
             branches:
               only:
                 - master
    jobs:
      - build