name: build

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron:  0 0 1 * *

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: make build

      - name: Push
        run: |
          git config --global user.name '${GITHUB_ACTOR}'
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git add -A
          git commit -m ':art: Daily build'
          git remote add upstream https://$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git push -u upstream master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GITHUB_ACTOR: ${{secrets.GITHUB_ACTOR}}
        GITHUB_REPOSITORY: ${{secrets.GITHUB_REPOSITORY}}